spring.application.name=ledgerly

# H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:ledgerlydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Hibernate auto-create tables from your entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 web console ? lets you browse your in-memory DB in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3.5-flash-lite